#!/bin/bash

# Install zsh
sudo apt update && sudo apt install -y \
    unzip \
    zsh \
    python3-pip \
    python3-venv \
    virtualenv \
    docker.io

# Installing virtualenv 'py'
if [[ ! -d ~/.config/envs/py ]]; then
    virtualenv ~/.config/envs/py -p $(which python3)
fi

# Attach my user to 'docker' user group
if [[ -z "$(which docker)" ]]; then
    echo \nAdding $USER to docker group ==============================
    sudo usermod -aG docker $USER
    echo \nDONE ======================================================
fi

# Install Oh My Zsh
if [[ ! -a ~/.oh-my-zsh ]]; then
    echo \nInstalling Oh My Zsh ======================================
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    echo \nDONE ======================================================
fi

# Install neovim
if [[ -z "$(which nvim)" ]]; then
    echo \nInstalling Neovim =========================================
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod u+x nvim.appimage
    ./nvim.appimage --appimage-extract
    ./squashfs-root/AppRun --version
    ## Expose neovim globally
    sudo mv squashfs-root /
    sudo ln -s /squashfs-root/AppRun /usr/bin/nvim
    echo \nDONE ======================================================
fi

# Install tmux
if [[ ! -a ~/.config/tmux/tmux.conf.local ]]; then
    echo \nInstalling tmux ===========================================
    git clone https://github.com/gpakosz/.tmux.git ~/.local/share/tmux
    mkdir -p ~/.config/tmux
    ln -s ~/.local/share/tmux/.tmux.conf ~/.config/tmux/tmux.conf
    cp ~/.local/share/tmux/.tmux.conf.local ~/.config/tmux/tmux.conf.local
    echo \nDONE ======================================================
fi

# Moving nvim dotfiles
if [[ ! -d ~/.config/nvim ]]; then
    echo \nMoving ./dotfiles/nvim to ~/.configs/nvim ================
    cp -r ./dotfiles/nvim ~/.configs/nvim
    echo \nDONE ======================================================
fi
